language: dart

dart:
 - 2.1.1
 - dev

dart_task:
 - test: --platform vm
   xvfb: false
 - test: --platform chrome
 - dartanalyzer: --fatal-warnings --fatal-infos .

matrix:
  include:
  # Only validate formatting using the dev release
  - dart: dev
    dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
