include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true

linter:
  rules:
    - avoid_private_typedef_functions
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - cascade_invocations
    - join_return_with_assignment
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_runtimeType_toString
    - package_api_docs
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - unnecessary_raw_strings
    - use_string_buffers
